### ISSUE TITLE
error on p8 init

### ISSUE THREAD

**Issue by geekhunger** [jozanza/p8#1]
Installed lua, moonscript and your tool (p8)
But when running `p8 init` I get this error ... any idea why?

I'm on OSX 10.11 El Capitan

```
AlexandsMacBook:cavemen alexanderschaefer$ p8 init

/usr/local/lib/node_modules/p8/src/p8-init:9
const { parse } = require('path')
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by jozanza** [comment]
@jack0088 it seems like you are probably using an older version of node. If that's the case, install node v6, and you should be good to go! Let me know if you need anymore help getting up and running 👍

**Comment by geekhunger** [comment]
that was it! thank you so much!
